if(CMAKE_Fortran_COMPILER_ID STREQUAL Intel)
  if(WIN32)
    set(FFLAGS /warn:declarations)
    # FIXME: this is a workaround for Intel Compiler icl bug: https://www.scivision.dev/intel-compiler-windows-bug-workaround
    set(CFLAGS /TP)
  else()
    set(FFLAGS -warn declarations)
  endif()
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL GNU)
  add_compile_options(-mtune=native)
  set(FFLAGS -fimplicit-none)
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL PGI)
  set(FFLAGS -Mdclchk)
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL Flang)

endif()
