name: ci_build
env:
   HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_build.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest  -parallel 2 --output-on-failure
      working-directory: build


  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install gcc lapack scalapack open-mpi

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest --parallel 2 --output-on-failure
      working-directory: build


  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build -G "MinGW Makefiles"

    - run: cmake --build build --parallel

    - run: ctest --parallel 2 --output-on-failure
      working-directory: build
